### PR TITLE
Added Dimmer2 support

### PR DESCRIPTION
**Pull request by chemelli74**
Dimmer2 is now supported by the library

### CODE REVIEW

**Comment by vistalba** [comment]
Confirmed, worked for me too if replaced inside docker of HASSIO.

**Comment by frodcab** [comment]
Confirmed, worked for me too with proper changes in homeassistant container

**Comment by vistalba** [comment]
Is it possible to merge this as the change? In docker isn't persistent so I've to do this after every container restart (server restart). It would be nice if there is a new release of the integration :) Thanks.

**Comment by chemelli74** [comment]
> Is it possible to merge this as the change? In docker isn't persistent so I've to do this after every container restart (server restart).

Restart HA from its own menu and not doing a off/on of the container ;-)

Simone

**Comment by vistalba** [comment]
> Restart HA from its own menu and not doing a off/on of the container ;-)

I know... but when updating from 0.111.4 to 0.112.0 it restarted everything so I had to edit the file again :(

**Comment by hakana** [comment]
Implemented

**Comment by chemelli74** [comment]
Git says closed without merge.
Did you implement the change without my PR ?
Should I delete it ?

Simone

**Comment by DaveRuijter** [comment]
@hakana can you please review what has happened here, it seems to me this code is not merged into master?

**Pull request closed without merging**
